//
// Timestamp.cpp
//
// $Id: //poco/1.3/Foundation/src/Timestamp.cpp#2 $
//
// Library: Foundation
// Package: DateTime
// Module:  Timestamp
//
// Copyright (c) 2004-2006, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#include <algorithm>
#include <libTimestamp/Timestamp.h>

#if defined(PLATFORM_OS_FAMILY_UNIX)
#include <time.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/times.h>
#elif defined(PLATFORM_OS_FAMILY_WINDOWS)
#include <libCommon/os/UnWindows.h>
#endif

#include <libCommon/CMyException.h>


namespace _timestamp_ {


Timestamp::Timestamp()
{
	update();
}


Timestamp::Timestamp(TimeVal tv)
{
	_ts = tv;
}


Timestamp::Timestamp(const Timestamp& other)
{
	_ts = other._ts;
}


Timestamp::~Timestamp()
{
}


Timestamp& Timestamp::operator = (const Timestamp& other)
{
	_ts = other._ts;
	return *this;
}


Timestamp& Timestamp::operator = (TimeVal tv)
{
	_ts = tv;
	return *this;
}


void Timestamp::swap(Timestamp& timestamp)
{
	std::swap(_ts, timestamp._ts);
}



Timestamp Timestamp::fromEpochTm(tm* t)
{
	return Timestamp(fromEpochTime(mktime(t)));
}

Timestamp Timestamp::fromEpochTime(std::time_t t)
{
	return Timestamp(TimeVal(t)*resolution());
}


Timestamp Timestamp::fromUtcTime(UtcTimeVal val)
{
	val -= (TimeDiff(0x01b21dd2) << 32) + 0x13814000;
	val /= 10;
	return Timestamp(val);
}


void Timestamp::update()
{
#if defined(PLATFORM_OS_FAMILY_WINDOWS)

	// poco库 实现原型 出现日期正确，时秒分不正确
	FILETIME ft;
	GetSystemTimeAsFileTime(&ft);
	ULARGE_INTEGER epoch; // UNIX epoch (1970-01-01 00:00:00) expressed in Windows NT FILETIME
	epoch.LowPart  = 0xD53E8000;
	epoch.HighPart = 0x019DB1DE;

	ULARGE_INTEGER ts;
	ts.LowPart  = ft.dwLowDateTime;
	ts.HighPart = ft.dwHighDateTime;
	ts.QuadPart -= epoch.QuadPart;
	_ts = ts.QuadPart/10;

#else
	struct timeval tv;
	if (gettimeofday(&tv, NULL))
		EXCEPTION_THROW(CommonException,"cannot get time of day")
	_ts = TimeVal(tv.tv_sec)*resolution() + tv.tv_usec;
	
#endif
}

_string_type Timestamp::localTimePrintf()
{
	struct tm * timeinfo;
	char szTime[30] = {0};
	time_t rawtime = epochTime();
	timeinfo = localtime ( &rawtime );
	sprintf ( szTime,"[%04d-%02d-%02d %02d:%02d:%02d]", 
		timeinfo->tm_year + 1900, timeinfo->tm_mon + 1,
		timeinfo->tm_mday,timeinfo->tm_hour,
		timeinfo->tm_min,timeinfo->tm_sec);

	return szTime;
}

_string_type	Timestamp::gmTimePrintf()
{
	struct tm * timeinfo;
	char szTime[30] = {0};
	time_t rawtime = epochTime();
	timeinfo = gmtime ( &rawtime );
	sprintf ( szTime,"[%04d-%02d-%02d %02d:%02d:%02d]", 
		timeinfo->tm_year + 1900, timeinfo->tm_mon + 1,
		timeinfo->tm_mday,timeinfo->tm_hour,
		timeinfo->tm_min,timeinfo->tm_sec);

	return szTime;
}

_string_type	Timestamp::DateString()
{
	struct tm * timeinfo = epochTM();
	char szTime[10] = {0};
	sprintf ( szTime,"%04d%02d%02d", 
		timeinfo->tm_year + 1900, timeinfo->tm_mon + 1,
		timeinfo->tm_mday );
	return szTime;
}

_string_type	Timestamp::DateTimeString()
{
	struct tm * timeinfo = epochTM();
	char szTime[25] = {0};
	sprintf ( szTime,"%04d%02d%02d%02d%02d%02d", 
		timeinfo->tm_year + 1900, timeinfo->tm_mon + 1,
		timeinfo->tm_mday,
		timeinfo->tm_hour, timeinfo->tm_min, timeinfo->tm_sec );
	return szTime;
}

//毫秒
_string_type	Timestamp::DateMilliString()
{
	struct tm * timeinfo = epochTM();
	char szTime[25] = {0};
	sprintf ( szTime,"%04d%02d%02d%02d%02d%02d%03d", 
		timeinfo->tm_year + 1900, timeinfo->tm_mon + 1,
		timeinfo->tm_mday,
		timeinfo->tm_hour, timeinfo->tm_min, timeinfo->tm_sec,
		_ts % resolution() / 1000);
	return szTime;
}

_string_type	Timestamp::DateMicroString()
{
	struct tm * timeinfo = epochTM();
	char szTime[25] = {0};
	sprintf ( szTime,"%04d%02d%02d%02d%02d%02d%06d", 
		timeinfo->tm_year + 1900, timeinfo->tm_mon + 1,
		timeinfo->tm_mday,
		timeinfo->tm_hour, timeinfo->tm_min, timeinfo->tm_sec, _ts % resolution() );
	return szTime;
}


#if defined(_WIN32)


Timestamp Timestamp::fromFileTimeNP(UInt32 fileTimeLow, UInt32 fileTimeHigh)
{
	ULARGE_INTEGER epoch; // UNIX epoch (1970-01-01 00:00:00) expressed in Windows NT FILETIME
	epoch.LowPart  = 0xD53E8000;
	epoch.HighPart = 0x019DB1DE;
	
	ULARGE_INTEGER ts;
	ts.LowPart  = fileTimeLow;
	ts.HighPart = fileTimeHigh;
	ts.QuadPart -= epoch.QuadPart;

	return Timestamp(ts.QuadPart/10);
}


void Timestamp::toFileTimeNP(UInt32& fileTimeLow, UInt32& fileTimeHigh) const
{
	ULARGE_INTEGER epoch; // UNIX epoch (1970-01-01 00:00:00) expressed in Windows NT FILETIME
	epoch.LowPart  = 0xD53E8000;
	epoch.HighPart = 0x019DB1DE;

	ULARGE_INTEGER ts;
	ts.QuadPart  = _ts*10;
	ts.QuadPart += epoch.QuadPart;
	fileTimeLow  = ts.LowPart;
	fileTimeHigh = ts.HighPart;
}

#endif



} // namespace Common
