#!/bin/sh

DIR=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
export CROSSTOOL_PATH=${DIR}
export LIB_PATH=${CROSSTOOL_PATH}/sysroots/target-arm
export PATH=${CROSSTOOL_PATH}/sysroots/x86_64-linux/bin/:$PATH
#export CC="arm-oe-linux-gnueabi-gcc  -march=armv7-a -mfloat-abi=softfp -mfpu=neon --sysroot=${LIB_PATH}"
export CC="arm-openwrt-linux-uclibcgnueabi-gcc"
export AS="arm-openwrt-linux-uclibcgnueabi-as "
export AR="arm-openwrt-linux-uclibcgnueabi-ar"
export ARCH="arm"
export LD="arm-openwrt-linux-uclibcgnueabi-ld"
#export CFLAGS=" -O2 -Wa,--noexecstack -fstack-protector -fexpensive-optimizations -frename-registers -fomit-frame-pointer -ftree-vectorize   -finline-functions -finline-limit=64   -Wno-error=maybe-uninitialized -Wno-error=unused-result  -fstack-protector-strong -pie -fpie"
export CROSS_COMPILE="arm-openwrt-linux-uclibcgnueabi-"
#export CXX="arm-oe-linux-gnueabi-g++  -march=armv7-a -mfloat-abi=softfp -mfpu=neon --sysroot=${LIB_PATH}"
export CXX="arm-openwrt-linux-uclibcgnueabi-g++"
#export CXXFLAGS=" -O2 -Wa,--noexecstack -fstack-protector -fexpensive-optimizations -frename-registers -fomit-frame-pointer -ftree-vectorize   -finline-functions -finline-limit=64   -Wno-error=maybe-uninitialized -Wno-error=unused-result  -fstack-protector-strong -pie -fpie -fvisibility-inlines-hidden"

#export LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now,-z,noexecstack"
export MAKE="make"
export NM="arm-openwrt-linux-uclibcgnueabi-nm"
export OBJCOPY="arm-openwrt-linux-uclibcgnueabi-objcopy"
export OBJDUMP="arm-openwrt-linux-uclibcgnueabi-objdump"
export RANLIB="arm-openwrt-linux-uclibcgnueabi-ranlib"
export READELF="arm-openwrt-linux-uclibcgnueabi-readelf"
export STRINGS="arm-openwrt-linux-uclibcgnueabi-strings"
export STRIP="arm-openwrt-linux-uclibcgnueabi-strip"
export CROSSCOMPILE_FLAG=1
export ADB_LOGIN_FUNC=0
